#!/usr/bin/env python3
"""Install tempo on this machine.

    python3 install.py install
    python3 install.py status
    python3 install.py uninstall

Nothing in the repo records where the repo lives. `install` resolves that here, at
install time, and bakes it into these generated artifacts:

    ~/.local/bin/tempo          shim -> this clone's tempo.py
    ~/.claude/skills/<name>     symlink -> this clone's skill, for each skill in SKILLS

So shipping to another machine is `git clone` then `python3 install.py install`, and
moving a clone is the same command run again from its new home. State in ~/.tempo is
never touched.
"""

import argparse
import os
import shlex
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BIN = os.path.expanduser("~/.local/bin")
SKILLS_DIR = os.path.expanduser("~/.claude/skills")
SKILLS = ["tempo"]  # directories under .claude/skills in this repo
SHIM = "tempo"

# Every generated shim carries this, so uninstall can tell a shim it wrote from an
# unrelated `tempo` someone else put on the PATH.
MARKER = "# generated by tempo install.py"


def _quote(path):
    return "'%s'" % path.replace("'", "'\\''")


def shim_body(python, script):
    return "#!/bin/sh\n%s -- re-run it to repoint, do not edit\nexec %s %s \"$@\"\n" % (
        MARKER, _quote(python), _quote(script))


def shim_path():
    return os.path.join(BIN, SHIM)


def is_ours(path):
    """True if `path` is a shim this installer generated."""
    try:
        with open(path) as f:
            return MARKER in f.read(len(MARKER) + 200)
    except (OSError, UnicodeDecodeError):
        return False


def shim_script(path):
    """The tempo.py a shim execs, or None if it cannot be read."""
    try:
        with open(path) as f:
            words = shlex.split(f.read().strip().splitlines()[-1])
        return words[2]
    except (OSError, ValueError, IndexError):
        return None


def write_shim(python=None, here=None):
    """Write the shim, refusing to overwrite a `tempo` that is not ours."""
    path = shim_path()
    if os.path.exists(path) and not is_ours(path):
        sys.exit("tempo: %s exists and was not written by tempo -- "
                 "move it aside and re-run" % path)
    os.makedirs(BIN, exist_ok=True)
    script = os.path.join(HERE if here is None else here, "tempo.py")
    with open(path, "w") as f:
        f.write(shim_body(python or sys.executable, script))
    os.chmod(path, 0o755)
    return path


def skill_target(name):
    return os.path.join(HERE, ".claude", "skills", name)


def link_skill(name):
    """Point ~/.claude/skills/<name> at this clone's skill.

    Never clobbers: an unrelated directory or a real file is left in place and
    reported, because that path may be something the user put there.
    """
    link = os.path.join(SKILLS_DIR, name)
    target = skill_target(name)
    if not os.path.isdir(target):
        return "missing in this clone: %s" % target
    os.makedirs(SKILLS_DIR, exist_ok=True)
    if os.path.islink(link):
        if os.path.realpath(link) == os.path.realpath(target):
            return "already linked"
        os.unlink(link)  # a link we can see is one a previous install wrote
        os.symlink(target, link)
        return "repointed"
    if os.path.exists(link):
        return "left alone (not a symlink -- remove it yourself to use the global skill)"
    os.symlink(target, link)
    return "linked"


def _is_inside(path, root):
    """True if `path` lies within `root`, compared by path component."""
    try:
        return os.path.commonpath([os.path.realpath(path), os.path.realpath(root)]) \
            == os.path.realpath(root)
    except ValueError:
        return False


def _nudge_problem():
    """Why nudges would not fire, or None. Tempo works without nudge, only blind."""
    if not shutil.which("nudge"):
        return "nudge is not on the PATH (tempo works, but sessions get no reminders)"
    r = subprocess.run(["nudge", "status"], capture_output=True, text=True)
    if r.returncode != 0:
        return "nudge is unhealthy: %s" % ((r.stdout + r.stderr).strip() or r.returncode)
    return None


def cmd_install(args):
    path = write_shim()
    print("installed tempo from %s" % HERE)
    print("  shim   %s" % path)
    for name in SKILLS:
        print("  skill  %s (%s)" % (os.path.join(SKILLS_DIR, name), link_skill(name)))
    print("  state  %s (created on first use)" % os.path.expanduser("~/.tempo"))
    if BIN not in os.environ.get("PATH", "").split(os.pathsep):
        print("\nnote: %s is not on your PATH, so `tempo` will not resolve.\n"
              "      add it to your shell profile, or call %s directly." % (BIN, path))
    problem = _nudge_problem()
    if problem:
        print("\nnote: %s" % problem)
    return 0


def cmd_uninstall(args):
    removed, left = [], []
    path = shim_path()
    if os.path.exists(path):
        if is_ours(path):
            os.unlink(path)
            removed.append(path)
        else:
            left.append("%s -- not written by tempo" % path)
    for name in SKILLS:
        link = os.path.join(SKILLS_DIR, name)
        if os.path.islink(link):
            if _is_inside(link, HERE):
                os.unlink(link)
                removed.append(link)
            else:
                left.append("%s -- points outside this clone" % link)
    for item in removed:
        print("removed    %s" % item)
    for item in left:
        print("left       %s" % item)
    if not removed and not left:
        print("nothing to uninstall")
    else:
        print("\nuninstalled. State in ~/.tempo was left alone.")
    return 0


def problems():
    """Everything wrong with the install, as short strings. Empty means healthy."""
    found = []
    path = shim_path()
    if not os.path.exists(path):
        found.append("shim missing: %s" % path)
    elif not is_ours(path):
        found.append("%s is not tempo's shim" % path)
    else:
        script = shim_script(path)
        if script and not os.path.exists(script):
            found.append("the shim's target is gone (did the clone move?): %s" % script)
    for name in SKILLS:
        link = os.path.join(SKILLS_DIR, name)
        if not os.path.islink(link):
            found.append("skill not linked: %s" % link)
        elif os.path.realpath(link) != os.path.realpath(skill_target(name)):
            found.append("skill %s points at a different clone: %s" % (name, os.path.realpath(link)))
    nudge = _nudge_problem()
    if nudge:
        found.append(nudge)
    return found


def cmd_status(args):
    found = problems()
    if not found:
        print("tempo  installed  %s" % HERE)
        return 0
    for item in found:
        print("problem  %s" % item)
    print("\nrepair: %s %s install" % (_quote(sys.executable), _quote(os.path.join(HERE, "install.py"))))
    return 1


def main(argv=None):
    p = argparse.ArgumentParser(prog="install.py", description=__doc__.splitlines()[0])
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("install").set_defaults(func=cmd_install)
    sub.add_parser("status").set_defaults(func=cmd_status)
    sub.add_parser("uninstall").set_defaults(func=cmd_uninstall)
    args = p.parse_args(argv)
    sys.exit(args.func(args))


if __name__ == "__main__":
    main()
